### PR TITLE
[CI] Fix Sample Apps Designs

### PR DESCRIPTION
**Pull request by theBeginner86**
**Description**

This PR fixes the sample apps designs that are used for E2E test of meshery adapters.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit ece74d3d9ef6d5f20485aea638b3c1307707b7c2 at: https://6482e1f27b91f4386f62cb2f--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2ec8ef9b2617115896aeb2ddeade2471280836fa at: https://6482e9ddd109683e33232e22--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0280bce5523938caa4e273b0f3ad299ea54393ef at: https://6482ecb058075900e52e72e3--service-mesh-patterns.netlify.app

**Comment by theBeginner86** [comment]
Screenshot 2023-06-09 at 2 54 21 PM

Screenshot 2023-06-09 at 2 54 55 PM

**Comment by theBeginner86** [comment]
@Revolyssup 
Would you please merge, I don't have access in this repo.

**Comment by Revolyssup** [comment]
> @Revolyssup Would you please merge, I don't have access in this repo.

The name of the file is bookinfo"withoutk8s" 
 Can you change the name?

**Comment by theBeginner86** [comment]
sure

**Comment by l5io** [comment]
🚀 Preview for commit 184561fb8e1313d95703719ad9a52dfb7cdffd25 at: https://6482f1be50f97f00980d4c43--service-mesh-patterns.netlify.app

**Comment by theBeginner86** [comment]
updated to booking.yaml

**Review by Revolyssup — APPROVED** [review]

**Pull request merged**
