### PR TITLE
Add version to Istio service

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
What ramifications does this have for existing patterns, for the pattern engine, for other components?

**Comment by leecalcote** [comment]
We need a discussion and a design spec update.

**Comment by leecalcote** [comment]
Oh, wait. I thought this PR was in the meshery-istio repo.

**Comment by Revolyssup** [comment]
> What ramifications does this have for existing patterns, for the pattern engine, for other components?

Let's discuss this on call today. I will clarify.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
