### PR TITLE
Footer Recreated

### LINKED ISSUE #55: [Site] Add the footer section
**Desired State of the Service Mesh Patterns site**

A `Footer` section needs to be added as per this [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=8838%3A14252) design.

---
### Contributor Resources
This website uses React and GitHub Pages. Site content is found under the [`master` branch](https://github.com/service-mesh-books/service-mesh-patterns/tree/master/src).
- See the [Contributing to Service Mesh Patterns Website](https://github.com/service-mesh-patterns/service-mesh-patterns/#readme) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- Layer5 [Brand Kit](https://layer5.io/company/brand)
- 📑 [Service Mesh Patterns in Meshery Catalog](https://meshery.io/catalog)
- 📖 [Service Mesh Patterns Book](https://layer5.io/learn/service-mesh-books/service-mesh-patterns)
- 🎨 [Site designs in Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5310%3A0). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Rohith-Raju**
Signed-off-by: rohith-raju <rohithraju488@gmail.com>

**Description**

This PR fixes #55 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 28d50eb89fdfb7d59ceed087a895cc880ff7b02b at: https://631885be8c07703a48c0cb0b--service-mesh-patterns.netlify.app

**Comment by leecalcote** [comment]
Sexy. 💃

**Comment by l5io** [comment]
🚀 Preview for commit a9fb127b38e5a839d1d8694fc81e2a2e6e65fa0a at: https://631a21537cb3cd055e730305--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 7c5a7c7e2a169cbb86efb7e6ff25a12faf6bdc6b at: https://631ee8a8d1b604631d9d7314--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 0b52db9e7b4613bd4d0f2b11a40db2d431a7e32b at: https://631ef4955fa5956f8dff8e4f--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 03817bec333acd047236e01b83265bde4a495150 at: https://631f0b949e1ad27eb8a7b3c3--service-mesh-patterns.netlify.app

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
