### PR TITLE
Updated new Twitter Logo

### LINKED ISSUE #121: Change Twitter Logo to Xi(New logo)
**Current State of the Service Mesh Patterns site**
Old logo is present on the website
image

**Desired State of the Service Mesh Patterns site**
Change twitter logo to X
image

---
### Contributor Resources
This website uses React and GitHub Pages. Site content is found under the [`master` branch](https://github.com/service-mesh-books/service-mesh-patterns/tree/master/src).
- See the [Contributing to Service Mesh Patterns Website](https://github.com/service-mesh-patterns/service-mesh-patterns/#readme) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- Layer5 [Brand Kit](https://layer5.io/company/brand)
- 📑 [Service Mesh Patterns in Meshery Catalog](https://meshery.io/catalog)
- 📖 [Service Mesh Patterns Book](https://layer5.io/learn/service-mesh-books/service-mesh-patterns)
- - 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by Karmpatel960**
**Description**
Changed Twitter old logo to new Twitter X logo with its svg file

This PR fixes #121 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
🚀 Preview for commit 10d3886f8eb487dba8d80a7eae243c53c37bd7c7 at: https://64ce237ba3461a2b6e47e836--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 020e0826b60879696bd91da57ca86dc83ab02032 at: https://64ce2ff22039343488a4a673--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 39616566de5030785f21318d85d77c5f2b863130 at: https://64cf5b48be3d0c29460eb19e--service-mesh-patterns.netlify.app

**Comment by Karmpatel960** [comment]
@thisiskaransgit ^ ^

**Comment by l5io** [comment]
🚀 Preview for commit 40d1fde6fdda900ecdd415149901c14fa77df1de at: https://64d641b10a5e86690c8fed6f--service-mesh-patterns.netlify.app

**Review by thisiskaransgit — APPROVED** [review]
Looks good to merge, thank you for your contribution :tada:

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
