### PR TITLE
[chore] Migrate from Core App type to Kubernetes MeshModel

### PR DESCRIPTION
**Pull request by theBeginner86**
**Description**

This PR migrates our old core designs to be compatible with MeshModels.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by theBeginner86** [comment]
we can hold on this PR, I'm adding more designs in this PR.

**Comment by l5io** [comment]
🚀 Preview for commit 1dcd0876bf5aadb2b88d6e3e9ed63dd491ea128a at: https://6484149101d6012a5e8be585--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e747c464b210b2f42cf4a78e6978090223441f8d at: https://64854b406038ce515f4f6753--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit cd6adae382177db04a2fd021e6f9e96153ab5958 at: https://64854c59ad38cc52b51d6dc3--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit e00ecf3a19a1fd09b740c1c73f28a84e38221a35 at: https://64855b6bf88be15b39cb22a2--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 12a9c4b45af9c679f9f24a2a020ca58923f14d97 at: https://64855e1842bbea5bb83ca1a8--service-mesh-patterns.netlify.app

**Comment by l5io** [comment]
🚀 Preview for commit 2ada0fab27ee51f232ac8f77361f1fb15b2743c7 at: https://648571e618fa9466af4ad929--service-mesh-patterns.netlify.app

**Comment by theBeginner86** [comment]
@Revolyssup 
This PR is ready for review and merge.

**Comment by Revolyssup** [comment]
> @Revolyssup This PR is ready for review and merge.

Have you tested deploying all these?

**Comment by theBeginner86** [comment]
I was not able to test IstioSpire design as there is some UI bug due to which CustomResources are not being handled properly in UI. // @Abhishek-Kumar09


Rest all designs are deployable.

**Comment by theBeginner86** [comment]
Also do we really need three different designs for bookInfo app?

> As all the three designs have exact same config. So probably we can remove two of them

**Comment by theBeginner86** [comment]
> I was not able to test IstioSpire design as there is some UI bug due to which CustomResources are not being handled properly in UI. // @Abhishek-kumar09
> 
> Rest all designs are deployable.


Screenshot 2023-06-11 at 12 35 48 PM

**Comment by l5io** [comment]
🚀 Preview for commit e10619af40504c34ee6946950997b128c951a078 at: https://64857634f88be16812cb1fb9--service-mesh-patterns.netlify.app

**Comment by Revolyssup** [comment]
> I was not able to test IstioSpire design as there is some UI bug due to which CustomResources are not being handled properly in UI. // @Abhishek-kumar09
> 
> Rest all designs are deployable.

Use mesheryctl or else curl  -H "<appropriate token>" -X POST http:localhost:9081/api/pattern/deploy -d `<the file>`

**Pull request merged**
